name: Build-deploy-image-docker

on:
  push:
    branches: master


jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        maven: [ '3.5.4', '3.6.3', '3.8.2' ]
        java: [ '8', '11', '16']
        
    steps:
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.2.1
        with:
          java-version: ${{ matrix.java }}
          maven-version: ${{ matrix.maven }}
      - name: Build with Maven
        run: mvn verify
  push_to_registry:
    name: Push Docker image to GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          pull: true
          push: true
          # cache-from: type=registry,ref=myorg/myrepository:latest
          # cache-to: type=inline
          tags: ghcr.io/spbgovbr/sistema_envio_planos_pgd_susep/enviopgdsusep:v1.0
